### ISSUE TITLE
action.yml in project root possible?

### ISSUE THREAD

**Issue by offa** [jenkins-infra/jenkins-security-scan#2]
Would it be possible to shorten the `uses:` to `uses: jenkins-infra/jenkins-security-scan@v1`, eg. by moving the action.yml to the project root?

Thanks to copy & paste it's not a big deal, but Actions are more usable without the need to remember full paths – `<user>/<repo>@<version>` is easy to use.

**Comment by daniel-beck** [comment]
Yeah, this is annoying, but GitHub [explicitly documents it as such](https://docs.github.com/en/actions/using-workflows/reusing-workflows):

> Reusable workflows are YAML-formatted files, very similar to any other workflow file. As with other workflow files, you locate reusable workflows in the `.github/workflows` directory of a repository. Subdirectories of the `workflows` directory are not supported.

Note that what you're using from the starter workflow is a full workflow, not just an action.

**Comment by offa** [comment]
I see, seems I mixed Actions and reusable workflows.
