### ISSUE TITLE
Parameterized Java version inconsistent with CD workflow

### ISSUE THREAD

**Issue by basil** [jenkins-infra/jenkins-security-scan#29]
In https://github.com/jenkins-infra/github-reusable-workflows/pull/31 it was discussed whether to make the Java version a parameter or to just use a modern version as an internal implementation detail, with a decided preference for the latter. This repository's choice of a parameterized value is inconsistent with that decision.

**Comment by daniel-beck** [comment]
Would #30 address this request? Or is the request to remove the ability to specify the version entirely?

**Comment by basil** [comment]
I meant inconsistent on an API level. Inconsisency on an implementation level is far less important.
